export * from "./Appointment";
export * from "./AddDoctorForm";
export * from "./Autocomplete";
export * from "./BigCalendar";
export * from "./Booking";
export * from "./ChatApp";
export * from "./ChatHeader";
export * from "./Chats";
// export * from "./Condition";
export * from "./Confirmation";
export * from "./ContactUs";
export * from "./Conversation";
export * from "./Credentials";
export * from "./Crop";
export * from "./Dashboard";
export * from "./EditProfile";
export * from "./EmptyChat";
export * from "./ErrorBoundary";
export * from "./Event";
export * from "./Fallback";
export * from "./Field";
export * from "./Footer";
export * from "./Filter";
export * from "./ForgotPassword";
export * from "./GridForm";
export * from "./Header";
export * from "./Input";
export * from "./ItemsList";
export * from "./Map";
export * from "./Message";
export * from "./MessagesList";
export * from "./Modal";
export * from "./ModalAllergy";
export * from "./ModalCreateService";
export * from "./ModalPatientAppointment";
export * from "./ModalDevices";
export * from "./ModalFiles";
export * from "./ModalInsurances";
export * from "./ModalInviteDoctor";
export * from "./ModalProcedure";
export * from "./ModalService";
export * from "./ModalSignUp";
export * from "./Patient";
export * from "./PatientAppointment";
export * from "./Payout";
export * from "./PaymentMethod";
export * from "./PendingPayments";
export * from "./PracticeMap";
export * from "./Pricing";
export * from "./Profile";
export * from "./ReduxComponent";
export * from "./ResetPassword";
export * from "./Results";
export * from "./Review";
export * from "./SearchForm";
export * from "./SearchWrapper";
export * from "./Services";
export * from "./ServicesModal";
export * from "./SideMenu";
export * from "./SignUpPatient";
export * from "./SignUpRequest";
export * from "./Slot";
export * from "./SlotForm";
export * from "./SlotPicker";
export * from "./Snackbar";
export * from "./Spinner";
export * from "./Toolbar";
export * from "./Tooltip";
export * from "./VideoApp";

/* Views */

// export { default as Admin } from "./Admin";
export { default as PatientCalendar } from "./PatientCalendar";
export { default as DoctorCalendar } from "./DoctorCalendar";
export { default as Chat } from "./Chat";
export { default as Chatbot } from "./Chatbot";
export { default as Home } from "./Home";
// export { default as Join } from "./Join";
export { default as Legal } from "./Legal";
export { default as Practice } from "./Practice";
export { default as Search } from "./Search";
export { default as Settings } from "./Settings";
export { default as SignIn } from "./SignIn";
export { default as SignUpDoctor } from "./SignUpDoctor";
// export { default as SignUpPractice } from "./SignUpPractice";
export { default as ThankYou } from "./ThankYou";
export { default as Verify } from "./Verify";
